name: Go

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: false
      upload:
        description: 'Upload: If want ignore'
        required: false
    push:
      branches:
        - master
        - main

jobs:
  upload:
    name: Build and Upload Release
    if: github.event.inputs.upload != 'y'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: default tag
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV
          else
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: go build && bash build_muiltarch.sh

      - name: Release
        # upload all files in release directory
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          tag_name: ${{ env.tag }}
          release_name: ${{ env.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

