name: Go

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: false
      upload:
        description: 'Upload: If want ignore'
        required: false
    push:
      branches:
        - master
        - main

jobs:
  upload:
    name: Build and Upload Release
    if: github.event.inputs.upload != 'y'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goarch: amd64
            goos: linux
          - goarch: amd64
            goos: darwin
          - goarch: arm64
            goos: linux
          - goarch: arm64
            goos: darwin
          - goarch: amd64
            goos: windows

    steps:
      - uses: actions/checkout@v2

      - name: default tag
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV
          else
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: |
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          bash build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: NekoXProxy_${{ matrix.goos }}_${{ matrix.goarch }}
          path: ./release/NekoXProxy_${{ matrix.goos }}_${{ matrix.goarch }}*

      #      - name: Release
      #        # upload all files in release directory
      #        uses: softprops/action-gh-release@v1
      #        with:
      #          files: release/*
      #          tag_name: ${{ env.tag }}
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: Release ${{ env.tag }}
          body: TODO New Release.
          draft: false
          prerelease: false
      - name: Uploading assets...
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release/NekoXProxy_${{ matrix.goos }}_${{ matrix.goarch }}*
          asset_name: NekoXProxy_${{ matrix.goos }}_${{ matrix.goarch }}

